blank_issues_enabled: false
contact_links:
  - name: Project Nebula Maintainer Documentation
    url: https://about.utdnebula.com/
    about: Get information about how to contribute to the project here.
  - name: Report a security vulnerability
    url: security@utdnebula.com
    about: Please report security vulnerabilities here.
  - name: General Contact
    url: https://about.utdnebula.com/contact
    about: Get in touch for any reason using the instructions here.
