name: Prettier Formatting Check
run-name: Running formatting check
on: [push]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i -g prettier prettier-plugin-tailwindcss
      - name: Prettier check
        run: |
          files=`npx prettier . -l` || st=$?
          echo status=`echo $st`>>"$GITHUB_ENV"
          echo files=`echo $files`>> "$GITHUB_ENV"
      - name: generate github check message
        run: .github/workflows/generateCheck.sh
